<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2010 You!
 * @link http://wwww.you.com
 */

/**
 * form file
 * 
 * @package 	d7ae673f
 * @subpackage 	
 * 
 * @author 		Your Name <your@email.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
PS::_rcf( '/css/form.css' );

//	I don't like this, I prefer bold-faced labels
PS::$afterRequiredLabel = null;
	
//	Uncomment for automatic tooltips
//	CPSjqToolsWrapper::create( 'tooltip', array( 'target' => '#ps-edit-form :input', 'tip' => '.ps-auto-tooltip', 'position' => 'center right', 'offset' => array( -2, 10 ), 'effect' => 'fade', 'opacity' => 0.7 ) );
?>
<div class="ps-edit-container">
	<div class="yiiForm">
<?php
		$_arFormOpts = array( 
			'id' => 'ps-edit-form', 
			'name' => 'ps-edit-form',
			'uiStyle' => PS::UI_JQUERY,

			'cssFiles' => array( 
				'/css/form.css',
				//	Add additional css here
			),
	
			'scriptFiles' => array( 
				//	Add any script files here
			),
	
			'formModel' => $model,

			//	We want error summary...
			'errorSummary' => true,

//	Uncomment if you are uploading from this form			
//			'enctype' => 'multipart/form-data',
			
			'validate' => true, 
			'validateOptions' => array(
				'errorClass' => 'ps-validate-error',
				'ignoreTitle' => true,
// @todo Place your extra validation options here...
//					'rules' => array(
//						'model_name[column_name]' => array(
//							'rule' => 'rule options',
//						),
//					),
//					'messages' => array(
//						'model_name[column_name]' => array(
//							'rule_name' => 'message',
//						),
//					),
			), 
		)
	);

	$_arFormOpts['fields'] = array(		array( PS::TEXT, 'app_name_text', array( 'size' => 60, 'maxlength' => 200 ) )
		array( PS::TEXT, 'app_url_text', array( 'size' => 60, 'maxlength' => 1024 ) )
		array( PS::TEXT, 'dev_app_url_text', array( 'size' => 60, 'maxlength' => 1024 ) )
array( PS::TEXT, 'server_id' )
array( PS::TEXT, 'dev_server_id' )
array( PS::TEXT, 'last_push_date' )
array( PS::TEXT, 'dev_last_push_date' )
		};
		
		CPSForm::create( $_arFormOpts );"
?>
	</div>
</div>