<?php
/*
 * This file was generated by the psYiiExtensions scaffolding package.
 * 
 * @copyright Copyright &copy; 2010 You!
 * @link http://wwww.you.com
 */

/**
 * admin view file
 * 
 * @package 	d7ae673f
 * @subpackage 	
 * 
 * @author 		Your Name <your@email.com>
 * @version 	SVN: $Id$
 * @since 		v1.0.6
 *  
 * @filesource
 * 
 */
	echo CPSDataGrid::createEx( , 
		array( 
			'formHeader' => array( 'title' => 'ManagedApp Manager', 'menuButtons' => array( 'new' ), 'itemName' => 'ManagedApp', ),
			'dataItem' => 'setting', 
			'columns' => array( 'app_name_text', 'app_url_text', 'dev_app_url_text', 'server_id', 'dev_server_id', 'last_push_date', 'dev_last_push_date', 'create_date', 'lmod_date' ),
			'actions' => array( 'edit', 'delete' ), 
			'sort' => ,
			'pages' => ,
			'pagerOptions' => array( 'header' => '' ),
			'linkView' => 'update',
		)
	);